version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - '8000-8095:8000-8095'
    privileged: true
    volumes:
      - ./nginx/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/conf.d:/etc/nginx/conf.d 

